apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-booking
  labels:
    app: acmeair-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair-booking
  template:
    metadata:
      labels:
        app: acmeair-booking
    spec:
      containers:
        - name: acmeair-booking
          image: netifi.azurecr.io/proteus-acmeair-booking:1.5.3.BUILD-SNAPSHOT
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              memory: "2Gi"
              cpu: "1500m"
          env:
            - name: PROTEUS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BOOKING_OPTS
              value: "$(BOOKING_OPTS) '-Dspring.config.name=application-prod' \
                                        '-Dnetifi.proteus.postgres.host=35.224.68.224' \
                                        '-Dnetifi.proteus.postgres.database=acmeairdb' \
                                        '-Dnetifi.proteus.postgres.username=postgres' \
                                        '-Dnetifi.proteus.postgres.password=acmeairdb' \
                                        '-Dnetifi.proteus.postgres.poolSize=40' \
                                        '-Dnetifi.proteus.broker.hostname=$(PROTEUS_HOSTNAME)' \
                                        '-Dnetifi.proteus.broker.port=8001'"
      imagePullSecrets:
        - name: netifi-private
